name: image-6
dependencies:
  - python=3.10
  - jupyter
  - pip:
    - vis
    - tf_explain
    - keras-vis
    - shap
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tensorflow
  - scikit-learn
  - opencv
  - keras
